spring.datasource.url=mysql://bc00a557a054bd:a560d99d@us-cdbr-iron-east-02.cleardb.net/heroku_fd7c3f7c56aefae?reconnect=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# mysql --host=us-cdbr-iron-east-02.cleardb.net --user=bc00a557a054bd --password=a560d99d --reconnect heroku_fd7c3f7c56aefae < arquivo.sql