import { Routes } from '@angular/router';
import { LayoutComponent } from './layout/layout.component';
import { authGuard } from './core/guards/auth.guard';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./pages/login/login.component').then(m => m.LoginComponent) },
  {
    path: '',
    component: LayoutComponent,
    canActivate: [authGuard],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'projects', loadComponent: () => import('./pages/projects/projects.component').then(m => m.ProjectsComponent) },
      { path: 'projects/new', loadComponent: () => import('./pages/project-workspace/project-form.component').then(m => m.ProjectFormComponent) },
      { path: 'projects/:id', loadComponent: () => import('./pages/project-workspace/project-workspace.component').then(m => m.ProjectWorkspaceComponent),
        children: [
          { path: '', redirectTo: 'summary', pathMatch: 'full' },
          { path: 'summary', loadComponent: () => import('./pages/project-workspace/project-summary.component').then(m => m.ProjectSummaryComponent) },
          { path: 'budgets', loadComponent: () => import('./pages/budget-worksheet/budget-list.component').then(m => m.BudgetListComponent) },
          { path: 'budgets/new', loadComponent: () => import('./pages/budget-worksheet/budget-form.component').then(m => m.BudgetFormComponent) },
          { path: 'budgets/:budgetId', loadComponent: () => import('./pages/budget-worksheet/budget-worksheet.component').then(m => m.BudgetWorksheetComponent) },
          { path: 'measurements', loadComponent: () => import('./pages/measurement/measurement-list.component').then(m => m.MeasurementListComponent) },
          { path: 'measurements/:mid', loadComponent: () => import('./pages/measurement/measurement-detail.component').then(m => m.MeasurementDetailComponent) },
          { path: 'daily-logs', loadComponent: () => import('./pages/daily-log/daily-log-list.component').then(m => m.DailyLogListComponent) },
          { path: 'daily-logs/:logId', loadComponent: () => import('./pages/daily-log/daily-log-detail.component').then(m => m.DailyLogDetailComponent) },
          { path: 'procurement', loadComponent: () => import('./pages/procurement/procurement-list.component').then(m => m.ProcurementListComponent) },
          { path: 'procurement/quotations', loadComponent: () => import('./pages/procurement/quotation-list.component').then(m => m.QuotationListComponent) },
          { path: 'procurement/inventory', loadComponent: () => import('./pages/procurement/inventory-list.component').then(m => m.InventoryListComponent) },
          { path: 'finance', loadComponent: () => import('./pages/finance/finance-dashboard.component').then(m => m.FinanceDashboardComponent) },
          { path: 'finance/invoices', loadComponent: () => import('./pages/finance/invoice-list.component').then(m => m.InvoiceListComponent) },
          { path: 'finance/cash-flow', loadComponent: () => import('./pages/finance/cash-flow.component').then(m => m.CashFlowComponent) },
          { path: 'contracts', loadComponent: () => import('./pages/project-workspace/contracts.component').then(m => m.ContractsComponent) },
          { path: 'schedule', loadComponent: () => import('./pages/project-workspace/schedule.component').then(m => m.ScheduleComponent) },
          { path: 'safety', loadComponent: () => import('./pages/safety/safety-list.component').then(m => m.SafetyListComponent) },
          { path: 'rfi', loadComponent: () => import('./pages/rfi/rfi-list.component').then(m => m.RfiListComponent) },
          { path: 'punch-list', loadComponent: () => import('./pages/punch-list/punch-list.component').then(m => m.PunchListComponent) },
          { path: 'submittals', loadComponent: () => import('./pages/submittals/submittal-list.component').then(m => m.SubmittalListComponent) },
          { path: 'documents', loadComponent: () => import('./pages/documents/document-list.component').then(m => m.DocumentListComponent) },
          { path: 'timesheets', loadComponent: () => import('./pages/time-tracking/timesheet-list.component').then(m => m.TimesheetListComponent) },
          { path: 'job-costing', loadComponent: () => import('./pages/job-costing/job-costing.component').then(m => m.JobCostingComponent) },
        ],
      },
      { path: 'sinapi', loadComponent: () => import('./pages/sinapi/sinapi.component').then(m => m.SinapiComponent) },
      { path: 'sinapi/materials', loadComponent: () => import('./pages/sinapi/material-list.component').then(m => m.MaterialListComponent) },
      { path: 'sinapi/:id', loadComponent: () => import('./pages/sinapi/composition-detail.component').then(m => m.CompositionDetailComponent) },
      { path: 'registry', loadComponent: () => import('./pages/registry/registry.component').then(m => m.RegistryComponent),
        children: [
          { path: '', redirectTo: 'clients', pathMatch: 'full' },
          { path: 'clients', loadComponent: () => import('./pages/registry/client-list.component').then(m => m.ClientListComponent) },
          { path: 'clients/new', loadComponent: () => import('./pages/registry/client-form.component').then(m => m.ClientFormComponent) },
          { path: 'clients/:clientId', loadComponent: () => import('./pages/registry/client-detail.component').then(m => m.ClientDetailComponent) },
          { path: 'employees', loadComponent: () => import('./pages/registry/employee-list.component').then(m => m.EmployeeListComponent) },
          { path: 'employees/:empId', loadComponent: () => import('./pages/registry/employee-detail.component').then(m => m.EmployeeDetailComponent) },
          { path: 'suppliers', loadComponent: () => import('./pages/registry/supplier-list.component').then(m => m.SupplierListComponent) },
          { path: 'suppliers/:suppId', loadComponent: () => import('./pages/registry/supplier-detail.component').then(m => m.SupplierDetailComponent) },
        ],
      },
      { path: 'equipment', loadComponent: () => import('./pages/equipment/equipment-list.component').then(m => m.EquipmentListComponent) },
      { path: 'notifications', loadComponent: () => import('./pages/notifications/notification-list.component').then(m => m.NotificationListComponent) },
      { path: 'commercial', loadComponent: () => import('./pages/commercial/commercial.component').then(m => m.CommercialComponent) },
      { path: 'reports', loadComponent: () => import('./pages/reports/reports.component').then(m => m.ReportsComponent) },
      { path: 'settings', loadComponent: () => import('./pages/settings/settings.component').then(m => m.SettingsComponent) },
      { path: 'profile', loadComponent: () => import('./pages/profile/profile.component').then(m => m.ProfileComponent) },
    ],
  },
  { path: '**', redirectTo: 'dashboard' },
];
