import { Routes } from '@angular/router';
import { RegistryHubComponent } from './registry-hub/registry-hub';
import { ClientListComponent } from './client-list/client-list';
import { EmployeeListComponent } from './employee-list/employee-list';
import { EmployeeFormComponent } from './employee-form/employee-form';
import { BankAccountListComponent } from './bank-account-list/bank-account-list';
import { TeamListComponent } from './team-list/team-list';
import { TeamFormComponent } from './team-form/team-form';
import { ClientFormComponent } from './client-form/client-form';
import { ContractorListComponent } from './contractor-list/contractor-list';
import { InspectorListComponent } from './inspector-list/inspector-list';
import { BdiListComponent } from './bdi-list/bdi-list';
import { SocialChargeListComponent } from './social-charge-list/social-charge-list';
import { UnitListComponent } from './unit-list/unit-list';
import { PaymentConditionListComponent } from './payment-condition-list/payment-condition-list';
import { CostCenterListComponent } from './cost-center-list/cost-center-list';
import { FinanceCategoryListComponent } from './finance-category-list/finance-category-list';
import { ProjectTypeListComponent } from './project-type-list/project-type-list';
import { DefaultStageListComponent } from './default-stage-list/default-stage-list';
import { IncidentTypeListComponent } from './incident-type-list/incident-type-list';
import { EpiListComponent } from './epi-list/epi-list';
import { ReportTemplateListComponent } from './report-template-list/report-template-list';

export const routes: Routes = [
  { path: '', component: RegistryHubComponent },
  { path: 'clients', component: ClientListComponent },
  { path: 'clients/new', component: ClientFormComponent },
  { path: 'clients/:id/edit', component: ClientFormComponent },
  { path: 'employees', component: EmployeeListComponent },
  { path: 'employees/new', component: EmployeeFormComponent },
  { path: 'employees/:id/edit', component: EmployeeFormComponent },
  { path: 'bank-accounts', component: BankAccountListComponent },
  { path: 'teams', component: TeamListComponent },
  { path: 'teams/new', component: TeamFormComponent },
  { path: 'teams/:id/edit', component: TeamFormComponent },
  { path: 'contractors', component: ContractorListComponent },
  { path: 'inspectors', component: InspectorListComponent },
  { path: 'bdi', component: BdiListComponent },
  { path: 'social-charges', component: SocialChargeListComponent },
  { path: 'units', component: UnitListComponent },
  { path: 'payment-methods', component: PaymentConditionListComponent },
  { path: 'cost-centers', component: CostCenterListComponent },
  { path: 'finance-categories', component: FinanceCategoryListComponent },
  { path: 'project-types', component: ProjectTypeListComponent },
  { path: 'default-stages', component: DefaultStageListComponent },
  { path: 'incident-types', component: IncidentTypeListComponent },
  { path: 'epis', component: EpiListComponent },
  { path: 'report-templates', component: ReportTemplateListComponent },
];
