CREATE TABLE etapa (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE orcamento (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    data_criacao DATETIME NOT NULL,
    valor_frete DECIMAL(10,2),
    valor_desconto DECIMAL(10,2),
    valor_total DECIMAL(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    observacao VARCHAR(200),
    data_hora_entrega DATETIME,
    codigo_cliente BIGINT(20) NOT NULL,
    codigo_usuario BIGINT(20) NOT NULL,
    FOREIGN KEY (codigo_cliente) REFERENCES cliente(codigo),
    FOREIGN KEY (codigo_usuario) REFERENCES usuario(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE item_orcamento (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    quantidade INTEGER NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    codigo_composicao BIGINT(20) NOT NULL,
    codigo_orcamento BIGINT(20) NOT NULL,
    FOREIGN KEY (codigo_composicao) REFERENCES composicao(codigo),
    FOREIGN KEY (codigo_orcamento) REFERENCES orcamento(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO etapa (nome) VALUES ('PROJETOS');
INSERT INTO etapa (nome) VALUES ('INSTALAÇÃO DO CANTEIRO DE OBRA');
INSERT INTO etapa (nome) VALUES ('MOVIMENTO DE TERRA');
INSERT INTO etapa (nome) VALUES ('ESCAVAÇÃO E ATERRO');
INSERT INTO etapa (nome) VALUES ('INFRA-ESTRUTURA');
INSERT INTO etapa (nome) VALUES ('SERVIÇOS GERAIS');
INSERT INTO etapa (nome) VALUES ('FUNDAÇÕES');
INSERT INTO etapa (nome) VALUES ('SUPERESTRUTURA');
INSERT INTO etapa (nome) VALUES ('PAREDES E PAINÉIS');
INSERT INTO etapa (nome) VALUES ('ALVENARIA DE PEÇAS CERÂMICAS PARA VEDAÇÃO');
INSERT INTO etapa (nome) VALUES ('ESQUADRIAS');
INSERT INTO etapa (nome) VALUES ('PORTÃO DE ENTRADA');
INSERT INTO etapa (nome) VALUES ('ESQUADRIAS DE MADEIRA');
INSERT INTO etapa (nome) VALUES ('ESQUADRIAS METÁLICAS');
INSERT INTO etapa (nome) VALUES ('COBERTURA');
INSERT INTO etapa (nome) VALUES ('ESTRUTURA DE MADEIRA');
INSERT INTO etapa (nome) VALUES ('TELHAS');
INSERT INTO etapa (nome) VALUES ('IMPERMEABILIZAÇÃO');
INSERT INTO etapa (nome) VALUES ('FORRO');
INSERT INTO etapa (nome) VALUES ('REVESTIMENTOS DE PAREDES INTERNAS E EXTERNAS');
INSERT INTO etapa (nome) VALUES ('ACABAMENTOS');
INSERT INTO etapa (nome) VALUES ('PISOS');
INSERT INTO etapa (nome) VALUES ('REGULARIZAÇÃO DE BASES');
INSERT INTO etapa (nome) VALUES ('ACABAMENTOS');
INSERT INTO etapa (nome) VALUES ('DEGRAUS, RODAPÉS, SOLEIRAS E PEITORIS');
INSERT INTO etapa (nome) VALUES ('INSTALAÇÕES HIDRÁULICAS');
INSERT INTO etapa (nome) VALUES ('INSTALAÇÕES HIDRÁULICAS');
INSERT INTO etapa (nome) VALUES ('RASGOS E ENCHIMENTOS');
INSERT INTO etapa (nome) VALUES ('ABRIGO E CAVALETE');
INSERT INTO etapa (nome) VALUES ('REDE DE ÁGUA FRIA - TUBOS E CONEXÕES DE PVC SOLDÁVEL MARROM');
INSERT INTO etapa (nome) VALUES ('REGISTROS');
INSERT INTO etapa (nome) VALUES ('RESERVATÓRIOS');
INSERT INTO etapa (nome) VALUES ('REDE DE ESGOTO - TUBOS E CONEXÕES DE PVC SOLDÁVEL BRANCO');
INSERT INTO etapa (nome) VALUES ('CAIXAS');
INSERT INTO etapa (nome) VALUES ('APARELHOS E METAIS')
INSERT INTO etapa (nome) VALUES ('INSTALAÇÕES ELÉTRICAS');
INSERT INTO etapa (nome) VALUES ('RASGOS E ENCHIMENTOS');
INSERT INTO etapa (nome) VALUES ('ENTRADA EM BAIXA TENSÃO');
INSERT INTO etapa (nome) VALUES ('ELETRODUTOS');
INSERT INTO etapa (nome) VALUES ('QUADROS E CAIXAS');
INSERT INTO etapa (nome) VALUES ('FIOS E CABOS');
INSERT INTO etapa (nome) VALUES ('DISJUNTORES');
INSERT INTO etapa (nome) VALUES ('INTERRUPTORES E TOMADAS');
INSERT INTO etapa (nome) VALUES ('LUMINÁRIAS EXTERNAS');
INSERT INTO etapa (nome) VALUES ('AQUECIMENTO');
INSERT INTO etapa (nome) VALUES ('INSTALAÇÕES DE TELEFONIA');
INSERT INTO etapa (nome) VALUES ('PINTURA');
INSERT INTO etapa (nome) VALUES ('PINTURA DE FORROS E PAREDES');
INSERT INTO etapa (nome) VALUES ('SERVIÇOS COMPLEMENTARES');
INSERT INTO etapa (nome) VALUES ('CALÇADA E MURO');
INSERT INTO etapa (nome) VALUES ('PAISAGISMO DA ÁREA EXTERNA');
INSERT INTO etapa (nome) VALUES ('PISCINA');
INSERT INTO etapa (nome) VALUES ('LIMPEZA FINAL');














